### ISSUE TITLE
Searching not working in overall Application

### ISSUE THREAD

**Issue by muhrizwan** [fajarghifar/point-of-sale#2]
Searching is not working, for example in categories section when we search some category, it's not working.
Also when I am trying to delete some category, category is not deleting.

**Comment by fajarghifar** [comment]
The search functionality has been updated to support filtering by both name and slug, so it should now work as expected for categories.
[Commit 736cd15](https://github.com/fajarghifar/laravel-point-of-sale/commit/1b7afc40efae0719f33c8340db78fa335005732e)

Regarding the issue with deleting categories, the category cannot be deleted because it is still associated with the product table. You need to remove or update the related products before the category can be deleted.
